services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_SCHEMA=public
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_URL=$
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - /docker/data/n8n-app:/home/node/.n8n
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${DB_POSTGRESDB_PORT}:25432"
    environment:
      POSTGRES_DB: ${DB_POSTGRESDB_DATABASE}
      POSTGRES_USER: ${DB_POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      PGPORT: ${DB_POSTGRESDB_PORT}
    volumes:
      - /data/docker/n8n/postgres:/var/lib/postgres/data

volumes:
  n8n_data:
    name: n8n_data
  postgres_data:
    name: postgres_data
